#!/bin/bash -eu

function setup-jdk-8() {
  echo "Downloading and Configuring Java 8"
  if [ ! -d "${OPENSHIFT_DATA_DIR}/jdk" ]; then
    mkdir -p ${OPENSHIFT_DATA_DIR}/jdk
  fi

  if [ ! -d "${OPENSHIFT_DATA_DIR}/jdk/jdk1.8.0_05" ]; then
    pushd ${OPENSHIFT_DATA_DIR}/jdk
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
    tar -zxf jdk-8u5-linux-x64.tar.gz
    rm jdk-8u5-linux-x64.tar.gz
  fi
  echo "Java 8 Downloaded"
}

setup-jdk-8
